language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'CREATE DATABASE brimir_test;' -U postgres
