default: &defaults
  ignore_user_agent_locale: false
  display_user_avatars: false
  default_user_avatar: 'identicon'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
